dist: trusty
sudo: required

language: scala

env:
  - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.12
  - 2.12.6

jdk:
  - oraclejdk8

notifications:
  slack:
    secure: Iyuxm9yOwUcT69bjgjqFnHTUQMRCIBAB3V0Xz2I2kir8gKYDsjjigKZgxFSAGMB9fF6KD72sAR0qwbIUt02jSM3qtkmKcAkaeqGQBKPJDiwWUGvgU5DVJuLH0huSvTePGNvPZ2YH60Y5KURJMF/0FtbqKL6Y+xfgAiZhrqvEAgw=

before_script:
  # default $SBT_OPTS is irrelevant to sbt launcher
  - unset SBT_OPTS
  - curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test scrooge
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION update

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION "project scrooge-generator-tests" coverage test coverageReport
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
